spring.application.name=Szyszka
spring.datasource.url=jdbc:mysql://localhost:3306/szyszkadb
spring.datasource.username=root
spring.datasource.password=1234qwer
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
jwt.secret=u5s4QqVdW2rP2ZfLk7X8yM1dJ3nB5hK7t9oL6mR1pS4=
jwt.expiration-ms=3600000

